### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Mu7aMNaD** [Baron010/top.gg-automatic-voter#1]
Unhandled Rejection: Error: No node found for selector: #votingvoted.

**Comment by Baron010** [comment]
fixed √

**Comment by Baron010** [comment]
> 
> 
> Unhandled Rejection: Error: No node found for selector: #votingvoted.

fixed √

**Comment by Baron010** [comment]
> 
> 
> Unhandled Rejection: Error: No node found for selector: #votingvoted.

fixed √
the problem was the site coold down
