### ISSUE TITLE
can you please make the script vote alot accounts once 

### ISSUE THREAD

**Issue by NoNameIRQ** [Baron010/top.gg-automatic-voter#10]
i have 30 account and i hope from you to develop the code to :
make it can vote alot of accounts once
when you vote the first account and close the browser
automatically then second account open and like so ....

**Comment by sortofasian** [comment]
try running 30 scripts

**Comment by ryokuchaaa** [comment]
> 

How can I do this? I tried to but it keeps closing the browser for the previous one I set up...

**Comment by TomiLahren** [comment]
use https://www.npmjs.com/package/auto-vote-topgg and for the `userDataDir` just pass in the different user data directories
