### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by Mu7aMNaD** [Baron010/top.gg-automatic-voter#2]
**Make the time when the voter vote little between like 14 to 12 hours random.
Because most of the discord clients logs when someone votes and to have someone that vote Exactly every 12 hours, It can detect it _Easily_**

**Comment by Baron010** [comment]
> 
> 
> **Make the time when the voter vote little between like 14 to 12 hours random. Because most of the discord clients logs when someone votes and to have someone that vote Exactly every 12 hours, It can detect it _Easily_**

It's already every **12h**, and Discord is to way far of this shit !! 
it's a "**top.gg**" voter that using cookies, not a "**Discord**" client .
