### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by RPGTheGreat** [Baron010/top.gg-automatic-voter#4]
What should i enter in cookie

**Comment by thedexterwhiz** [comment]
Bro go to top.gg, sign in and go to your bot vote page. Now click on the lock icon beside of https and click cookie in that. Now choose top.gg and click connect ssid. Now you will get the cookie

**Comment by RPGTheGreat** [comment]
I can't find in chorme

**Comment by thedexterwhiz** [comment]
Bro i did it in chrome

**Comment by thedexterwhiz** [comment]
https://ibb.co/MM7ky36
https://ibb.co/kHN7Xf8
https://ibb.co/59tFcDz

**Comment by PiggyAwesome** [comment]
> https://ibb.co/MM7ky36
> https://ibb.co/kHN7Xf8
> https://ibb.co/59tFcDz

whitch cookie should i insert

**Comment by AQUIAL** [comment]
**How do I get it on Android mobile :/**

**Comment by Baron010** [comment]
> **How do I get it on Android mobile :/**

You cant Actually, unless u got an RDP

**Comment by ahmed665ygfu** [comment]
bro what should i chooise exactly
https://ibb.co/tcgLf8w
https://ibb.co/48nN9FL
https://ibb.co/K6d5md8
https://ibb.co/gvKKB1Z

**Comment by Ahmadgm** [comment]
Connect.sid 
I found the answer

**Comment by KL-AE2160** [comment]
@AQUIAL you can find on mobile, but use 'kiwi browser ', it provides devtools like chrome
