### ISSUE TITLE
they added a video before vote button shown

### ISSUE THREAD

**Issue by almadrasa** [Baron010/top.gg-automatic-voter#5]
is the script still work now?

**Comment by karimawii** [comment]
just open the code with any code editing software like Visual Studio Code and edit line 22 to be 22000 instead of 10000 like that:
`	await new Promise((resolve)=>setTimeout(() => {
		page.click('#votingvoted');
        resolve();
	}, 22000));`

**Comment by millysecurity** [comment]
> just open the code with any code editing software like Visual Studio Code and edit line 21 to be 22000 instead of 10000 like that:
> ![image](https://user-images.githubusercontent.com/69881381/103279265-10494b80-49d6-11eb-9dad-ae54ac8916d5.png)
> 
> Download Visual Studio Code from: https://code.visualstudio.com/?wt.mc_id=vscom_downloads

This doesn't work because the video continues to play until you click the "No Thanks" button shown here..

![Screenshot](https://i.imgur.com/WxWrIMr.png)
