### ISSUE TITLE
they add recaptcha ,now it appear always before voting

### ISSUE THREAD

**Issue by almadrasa** [Baron010/top.gg-automatic-voter#7]

**Comment by almadrasa** [comment]
i try puppeteer puppeteer-extra, but the recaptcha still appear

**Comment by almadrasa** [comment]
another thing: when i vote regularly from my navigator (which firfox) recaptcha doesn't appear,
BUT in pupputter it's always block the voting ,
also voting doesn't worth solving recaptcha, cuz that come with cost
so the only way for now is work around it by **prevent the site from detecting pupputer**
### prevent the site from detecting pupputer
i try 
> puppeteer-extra-plugin-stealth
but doesn't work, but u still to check it maybe i did something wrong

**Comment by Mululu** [comment]
Any news?

Thank you
